######################################################################
# Automatically generated by qmake (3.0) Fri Jul 29 00:45:16 2016
######################################################################

TEMPLATE = app
TARGET = daemon
INCLUDEPATH += .

# Input
SOURCES += daemon.cpp
